services:
#  mysql-service:
#    image: mysql:8.0
#    container_name: mysql-container
#    environment:
#     MYSQL_ROOT_PASSWORD: tiger
#     MYSQL_DATABASE: crud_for_git_docker
#    ports:
#    - "3307:3306" # Host port 3307 → Container port 3306
#    volumes:
#    - ./docker-mysql-backup-data:/var/lib/mysql
#    networks:
#    - first-spring-net
    
  app:
    build: .                # builds your Dockerfile in current folder
    image: premchand2597/prem-first-spring-boot:v02
    container_name: prem-first-spring-container
    ports:
    - "8081:8080" # Host port 8081 → Container port 8080
    environment:
#     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/crud_for_git_docker
     SPRING_DATASOURCE_URL: jdbc:mysql://192.168.31.94:3306/crud_for_git_docker
     SPRING_DATASOURCE_USERNAME: springuser
     SPRING_DATASOURCE_PASSWORD: tiger
     SPRING_JPA_HIBERNATE_DDL_AUTO: update
     SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect  
#    depends_on:
#     - mysql-service
#    networks:
#     - first-spring-net
#     
#networks:
# first-spring-net:
